### ISSUE TITLE
When clicking on the duct it throws an error

### ISSUE THREAD

**Issue by CassieRoseZA** [gniftygnome/ductwork#5]
![image](https://github.com/gniftygnome/ductwork/assets/13422754/03b3cbcb-e0c8-4971-a11a-4aa3e8838ce9)

**Comment by gniftygnome** [comment]
What version of Ductwork are you running, and on what version of Minecraft?

**Comment by gniftygnome** [comment]
> It also kicks me as shown in thw first image

I assume you are talking about the broken 0.7.100 release (which was only for 1.20.3 anyway).

Please instead try 0.7.101, which actually fixes the issue, for both 1.20.3 and 1.20.4.
